spring:
  data:
    mongodb:
      uri: mongodb+srv://poornimamendon99_db_user:%40%40@cluster0.mhabb0s.mongodb.net/moviebookingdb?retryWrites=true&w=majority
  application:
    name: movie-booking-app
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   consumer:
  #     group-id: moviebooking-group
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #   listener:
  #     missing-topics-fatal: false
    
server:
  port: 5000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.apache.kafka: WARN
    com.moviebookingapp.backend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

